### ISSUE TITLE
Basic example not compile

### ISSUE THREAD

**Issue by Testato** [FWeinb/NTPClient#1]
You ned pass a value on costructor inizialization in the sketch, or if you prefer, you can add an empty constructor to the library

**Comment by FWeinb** [comment]
Thanks for reporting. I update this library to 2.0.0 and removed the need for calling `timeClient.begin()` completely.

**Comment by Testato** [comment]
Thanks to you for this library, i will test 2.0version tomorrow 
A question: is there an internal real time clock in the library ? Example, if i remove update from loop the time is synced only at boot on setup, and after the clock continue to work also without internet ?

**Comment by FWeinb** [comment]
Yes the Time will be continued but only based on the return value of `millis()` I have no idea how accurate this is. I could imagen that you would get quite a bit of shift in time over a long period. I have to investigate a little further to account for the initial offset that is created to account for the time it takes to process the UDP returned value.

**Comment by Testato** [comment]
Process the returned time need a big time ? It is strange, the esp is an 80Mhz mcu (and 160MHz if you want) i think he need about zero seconds for parse the UDP returned data.

**Comment by FWeinb** [comment]
No the time of the parsing is not that big but there could be some network related delays in getting the UDP data.
